-- Generated by scripts/hypr2lua.
-- Source: /home/hancore/.config/omarchy/themes/shadesofjade/hyprland.conf

hl.config({
  general = {
    col = {
      active_border = {
        colors = { "rgba(00a86bee)", "rgba(C3FCB8ee)" },
        angle = 45,
      },
      inactive_border = "rgb(00110b)",
    },
    border_size = 2,
    gaps_in = 3,
    gaps_out = 3,
  },
  decoration = {
    rounding = 2,
    rounding_power = 3,
    shadow = {
      enabled = true,
      render_power = 16,
      range = 8,
      color = "rgba(6,11,22, 0.8)",
    },
  },
})
